### ISSUE TITLE
Whatsapp room link returning 401

### ISSUE THREAD

**Issue by matt-l-w** [tulir/mautrix-docs#4]
Hello! Thanks for putting all of this together - it's extremely useful. I wanted to engage a bit more with the community so I was trying to joing the whatsapp room with the link listed on [this page](https://docs.mau.fi/bridges/go/whatsapp/index.html).

For ease of reading, the link is: `https://matrix.to/#/#whatsapp:maunium.net`

I'm signed in to my own Synapse server with the Element web client. After going through the various redirects in a browser, I receive the message

```
#whatsapp:maunium.net is not accessible at this time.

Try again later, or ask a room admin to check if you have access.

M_UNKNOWN was returned while trying to access the room. If you think you're seeing this message in error, please submit a bug report.
```

Checking the logs shows this request returning a 401.

<details>
  <summary>See logs</summary>
       <pre>
        <code>
matrix_1    | 2021-07-31 10:09:59,349 - synapse.http.federation.well_known_resolver - 253 - INFO - GET-11154 - Fetching https://maunium.net/.well-known/matrix/server
matrix_1    | 2021-07-31 10:09:59,487 - synapse.http.federation.well_known_resolver - 190 - INFO - GET-11154 - Response from .well-known: {'m.server': 'federation.mau.chat'}
matrix_1    | 2021-07-31 10:09:59,489 - twisted - 258 - INFO - GET-11154 - b'/etc/resolv.conf' changed, reparsing
matrix_1    | 2021-07-31 10:09:59,490 - twisted - 258 - INFO - GET-11154 - Resolver added ('127.0.0.11', 53) to server list
matrix_1    | 2021-07-31 10:10:01,195 - synapse.http.matrixfederationclient - 598 - INFO - GET-11154 - {GET-O-1} [maunium.net] Got response headers: 401 Unauthorized
matrix_1    | 2021-07-31 10:10:01,195 - synapse.http.matrixfederationclient - 676 - WARNING - GET-11154 - {GET-O-1} [maunium.net] Request failed: GET matrix://maunium.net/_matrix/federation/v1/query/directory?room_alias=%23whatsapp%3Amaunium.net: HttpResponseException('401: Unauthorized')
matrix_1    | 2021-07-31 10:10:01,196 - root - 259 - WARNING - GET-11154 - Error retrieving alias
matrix_1    | 2021-07-31 10:10:01,196 - synapse.http.server - 88 - INFO - GET-11154 - <XForwardedForRequest at 0x7f204f08bd00 method='GET' uri='/_matrix/client/r0/directory/room/%23whatsapp%3Amaunium.net' clientproto='HTTP/1.1' site='8008'> SynapseError: 502 - Failed to fetch alias
matrix_1    | 2021-07-31 10:10:01,197 - synapse.access.http.8008 - 389 - INFO - GET-11154 - 18.168.47.123 - 8008 - {None} Processed request: 1.852sec/-0.000sec (0.010sec, 0.000sec) (0.000sec/0.000sec/1) 55B 502 "GET /_matrix/client/r0/directory/room/%23whatsapp%3Amaunium.net HTTP/1.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0" [0 dbevts]
        </code>
  </pre>
</details>

I'm pretty new to Matrix - any advice here would be appreciated!

**Comment by tulir** [comment]
Your federation is misconfigured. It looks like there's a valid .well-known file, but it doesn't specify a port. The default port is 8448, but your server isn't responding on that port. 443 does respond fine, so you probably just need to add `:443` at the end of the target domain in the .well-known file.

**Comment by matt-l-w** [comment]
@tulir - thanks for checking for me. You were right - the port was all that was needed.

In case anyone else finds this - after your suggestion I found some helpful information (in the matrix docs of all places - seems obvious now) about [troubleshooting federation issues](https://matrix-org.github.io/synapse/latest/federate.html#troubleshooting). Most notably their tool to [test federation config](https://federationtester.matrix.org).
